# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
# TODO: update the name of the project
name: "include_dbt_kids_first"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
# TODO: update the profile name to match the profile name in profiles.yml
profile: "include-dbt-kids-first"

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  # TODO: update the model name below to match name above
  include-dbt-kids-first:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view

# Grant access to schemas for analyst groups and service accounts.
# TODO: add new schemas as needed.
# on-run-end:
#   # Grant on base schema
#   - 'grant usage on schema "{{ target.schema }}" to d3b_analysts, bix_scientist_group, d3b_superuser_ro, svc_dbt, svc_dgd'
#   - 'grant select on all tables in schema "{{ target.schema }}" to d3b_analysts, bix_scientist_group, d3b_superuser_ro, svc_dbt, svc_dgd'

seeds:
  quote_columns: true
  schema: import
