name: ftd
version: 1.0.0
profile: include
model-paths:
- models

macro-paths:
- macros
clean-targets:
- target
- dbt_packages
models:
  aecom:
    aecom_ftd_condition:
      +schema: aecom_ftd_data
      +materialized: table
    aecom_ftd_participant:
      +schema: aecom_ftd_data
      +materialized: table
    aecom_ftd_study:
      +schema: aecom_ftd_data
      +materialized: table
