name: tgt
version: 1.0.0
profile: aecom
model-paths:
- models
macro-paths:
- macros
clean-targets:
- target
- dbt_packages
vars:
  target_schema: fallback_schema
  source_table: aecom_src_combined
models:
  tgt:
    +materialized: table
    tgt_participant: null
    tgt_measurement: null
    tgt_condition: null
    tgt_event: null
    tgt_study: null
